#!/usr/bin/env python
"""Populate all .po files with translations for all 14 languages."""
import os
import re

LANGUAGES = ['es', 'fr', 'de', 'pt', 'it', 'ru', 'zh_HAns', 'ar', 'ja', 'ko', 'hi', 'tr', 'nl', 'pl']

TRANSLATIONS = {
    "Dashboard": {"es": "Panel de Control", "fr": "Tableau de bord", "de": "Dashboard", "pt": "Painel", "it": "Dashboard", "ru": "Панель управления", "zh_HAns": "控制台", "ar": "لوحة التحكم", "ja": "ダッシュボード", "ko": "대시보드", "hi": "डैशबोर्ड", "tr": "Kontrol Paneli", "nl": "Dashboard", "pl": "Panel"},
    "Profile": {"es": "Perfil", "fr": "Profil", "de": "Profil", "pt": "Perfil", "it": "Profilo", "ru": "Профиль", "zh_HAns": "个人资料", "ar": "الملف الشخصي", "ja": "プロフィール", "ko": "프로필", "hi": "प्रोफाइल", "tr": "Profil", "nl": "Profiel", "pl": "Profil"},
    "Hello, <strong>%(name)s</strong>": {"es": "Hola, <strong>%(name)s</strong>", "fr": "Bonjour, <strong>%(name)s</strong>", "de": "Hallo, <strong>%(name)s</strong>", "pt": "Olá, <strong>%(name)s</strong>", "it": "Ciao, <strong>%(name)s</strong>", "ru": "Привет, <strong>%(name)s</strong>", "zh_HAns": "你好，<strong>%(name)s</strong>", "ar": "مرحبا، <strong>%(name)s</strong>", "ja": "こんにちは、<strong>%(name)s</strong>", "ko": "안녕하세요, <strong>%(name)s</strong>", "hi": "नमस्ते, <strong>%(name)s</strong>", "tr": "Merhaba, <strong>%(name)s</strong>", "nl": "Hallo, <strong>%(name)s</strong>", "pl": "Cześć, <strong>%(name)s</strong>"},
    "Chat Support": {"es": "Chat de Soporte", "fr": "Chat de Support", "de": "Chat-Support", "pt": "Suporte via Chat", "it": "Chat di Supporto", "ru": "Чат поддержки", "zh_HAns": "在线客服", "ar": "دردشة الدعم", "ja": "チャットサポート", "ko": "채팅 지원", "hi": "चैट सहायता", "tr": "Sohbet Desteği", "nl": "Chat Ondersteuning", "pl": "Wsparcie na Czacie"},
    "Logout": {"es": "Cerrar sesión", "fr": "Déconnexion", "de": "Abmelden", "pt": "Sair", "it": "Esci", "ru": "Выйти", "zh_HAns": "退出登录", "ar": "تسجيل الخروج", "ja": "ログアウト", "ko": "로그아웃", "hi": "लॉग आउट", "tr": "Çıkış Yap", "nl": "Uitloggen", "pl": "Wyloguj"},
    "Change photo": {"es": "Cambiar foto", "fr": "Changer la photo", "de": "Foto ändern", "pt": "Alterar foto", "it": "Cambia foto", "ru": "Изменить фото", "zh_HAns": "更换照片", "ar": "تغيير الصورة", "ja": "写真を変更", "ko": "사진 변경", "hi": "फोटो बदलें", "tr": "Fotoğraf Değiştir", "nl": "Foto wijzigen", "pl": "Zmień zdjęcie"},
    "Customer": {"es": "Cliente", "fr": "Client", "de": "Kunde", "pt": "Cliente", "it": "Cliente", "ru": "Клиент", "zh_HAns": "客户", "ar": "عميل", "ja": "お客様", "ko": "고객", "hi": "ग्राहक", "tr": "Müşteri", "nl": "Klant", "pl": "Klient"},
    "Transactions": {"es": "Transacciones", "fr": "Transactions", "de": "Transaktionen", "pt": "Transações", "it": "Transazioni", "ru": "Транзакции", "zh_HAns": "交易记录", "ar": "المعاملات", "ja": "取引", "ko": "거래 내역", "hi": "लेन-देन", "tr": "İşlemler", "nl": "Transacties", "pl": "Transakcje"},
    "Cards": {"es": "Tarjetas", "fr": "Cartes", "de": "Karten", "pt": "Cartões", "it": "Carte", "ru": "Карты", "zh_HAns": "银行卡", "ar": "البطاقات", "ja": "カード", "ko": "카드", "hi": "कार्ड", "tr": "Kartlar", "nl": "Kaarten", "pl": "Karty"},
    "Local Transfer": {"es": "Transferencia Local", "fr": "Transfert Local", "de": "Lokale Überweisung", "pt": "Transferência Local", "it": "Trasferimento Locale", "ru": "Местный перевод", "zh_HAns": "本地转账", "ar": "تحويل محلي", "ja": "国内送金", "ko": "국내 이체", "hi": "स्थानीय हस्तांतरण", "tr": "Yerel Transfer", "nl": "Lokale Overschrijving", "pl": "Przelew Lokalny"},
    "International Wire": {"es": "Transferencia Internacional", "fr": "Virement International", "de": "Internationale Überweisung", "pt": "Transferência Internacional", "it": "Bonifico Internazionale", "ru": "Международный перевод", "zh_HAns": "国际汇款", "ar": "تحويل دولي", "ja": "海外送金", "ko": "국제 송금", "hi": "अंतर्राष्ट्रीय हस्तांतरण", "tr": "Uluslararası Havale", "nl": "Internationale Overboeking", "pl": "Przelew Międzynarodowy"},
    "Available Balance": {"es": "Saldo Disponible", "fr": "Solde Disponible", "de": "Verfügbares Guthaben", "pt": "Saldo Disponível", "it": "Saldo Disponibile", "ru": "Доступный баланс", "zh_HAns": "可用余额", "ar": "الرصيد المتاح", "ja": "利用可能残高", "ko": "사용 가능 잔액", "hi": "उपलब्ध शेष राशि", "tr": "Kullanılabilir Bakiye", "nl": "Beschikbaar Saldo", "pl": "Dostępne Saldo"},
    "Account Number:": {"es": "Número de Cuenta:", "fr": "Numéro de Compte:", "de": "Kontonummer:", "pt": "Número de Conta:", "it": "Numero di Conto:", "ru": "Номер счета:", "zh_HAns": "账户号码：", "ar": "رقم الحساب:", "ja": "口座番号：", "ko": "계좌 번호:", "hi": "खाता संख्या:", "tr": "Hesap Numarası:", "nl": "Rekeningnummer:", "pl": "Numer Konta:"},
    "Your account is currently frozen. Please contact support.": {"es": "Su cuenta está congelada. Por favor contacte soporte.", "fr": "Votre compte est actuellement gelé. Veuillez contacter le support.", "de": "Ihr Konto ist derzeit gesperrt. Bitte kontaktieren Sie den Support.", "pt": "Sua conta está congelada. Por favor contate o suporte.", "it": "Il tuo conto è attualmente bloccato. Contatta il supporto.", "ru": "Ваш счет заморожен. Пожалуйста, свяжитесь со службой поддержки.", "zh_HAns": "您的账户已被冻结，请联系客服。", "ar": "حسابك مجمد حاليًا. يرجى الاتصال بالدعم.", "ja": "アカウントが凍結されています。サポートにお問い合わせください。", "ko": "계정이 동결되었습니다. 지원팀에 문의하세요.", "hi": "आपका खाता अभी फ्रीज़ है। कृपया सहायता से संपर्क करें।", "tr": "Hesabınız şu anda dondurulmuştur. Destek ile iletişime geçin.", "nl": "Uw account is momenteel bevroren. Neem contact op met support.", "pl": "Twoje konto jest zamrożone. Skontaktuj się z pomocą techniczną."},
    "Your account is currently FROZEN.": {"es": "Su cuenta está actualmente CONGELADA.", "fr": "Votre compte est actuellement GELÉ.", "de": "Ihr Konto ist derzeit GESPERRT.", "pt": "Sua conta está atualmente CONGELADA.", "it": "Il tuo conto è attualmente BLOCCATO.", "ru": "Ваш счет ЗАМОРОЖЕН.", "zh_HAns": "您的账户已被冻结。", "ar": "حسابك مجمد حاليًا.", "ja": "アカウントが凍結中です。", "ko": "계정이 현재 동결되어 있습니다.", "hi": "आपका खाता अभी फ्रीज़ है।", "tr": "Hesabınız şu anda DONDURULMUŞTUR.", "nl": "Uw account is momenteel BEVROREN.", "pl": "Twoje konto jest aktualnie ZAMROŻONE."},
    "Contact Customer Care": {"es": "Contactar Servicio al Cliente", "fr": "Contacter le Service Client", "de": "Kundendienst kontaktieren", "pt": "Contactar Atendimento ao Cliente", "it": "Contatta il Servizio Clienti", "ru": "Связаться со службой поддержки", "zh_HAns": "联系客服", "ar": "الاتصال بخدمة العملاء", "ja": "カスタマーケアに連絡", "ko": "고객 서비스 문의", "hi": "ग्राहक सेवा से संपर्क करें", "tr": "Müşteri Hizmetleri ile İletişime Geç", "nl": "Klantenservice Contacteren", "pl": "Skontaktuj się z Obsługą Klienta"},
    "Transfer": {"es": "Transferencia", "fr": "Transfert", "de": "Überweisung", "pt": "Transferência", "it": "Trasferimento", "ru": "Перевод", "zh_HAns": "转账", "ar": "تحويل", "ja": "送金", "ko": "이체", "hi": "स्थानांतरण", "tr": "Transfer", "nl": "Overschrijving", "pl": "Przelew"},
    "Deposit": {"es": "Depósito", "fr": "Dépôt", "de": "Einzahlung", "pt": "Depósito", "it": "Deposito", "ru": "Депозит", "zh_HAns": "存款", "ar": "إيداع", "ja": "入金", "ko": "입금", "hi": "जमा", "tr": "Para Yatırma", "nl": "Storting", "pl": "Wpłata"},
    "Apply for loan": {"es": "Solicitar préstamo", "fr": "Demander un prêt", "de": "Kredit beantragen", "pt": "Solicitar empréstimo", "it": "Richiedi un prestito", "ru": "Подать заявку на кредит", "zh_HAns": "申请贷款", "ar": "طلب قرض", "ja": "ローンを申請", "ko": "대출 신청", "hi": "ऋण के लिए आवेदन करें", "tr": "Kredi Başvurusu Yap", "nl": "Lening Aanvragen", "pl": "Złóż wniosek o pożyczkę"},
    "Request Card": {"es": "Solicitar Tarjeta", "fr": "Demander une Carte", "de": "Karte anfordern", "pt": "Solicitar Cartão", "it": "Richiedi Carta", "ru": "Запросить карту", "zh_HAns": "申请银行卡", "ar": "طلب بطاقة", "ja": "カードを申請", "ko": "카드 신청", "hi": "कार्ड के लिए आवेदन करें", "tr": "Kart Talep Et", "nl": "Kaart Aanvragen", "pl": "Zamów Kartę"},
    "Set / Change Transaction PIN": {"es": "Establecer / Cambiar PIN", "fr": "Définir / Modifier le PIN", "de": "PIN setzen / ändern", "pt": "Definir / Alterar PIN", "it": "Imposta / Cambia PIN", "ru": "Установить / изменить PIN", "zh_HAns": "设置/更改交易密码", "ar": "تعيين / تغيير رمز المعاملة", "ja": "取引PINを設定/変更", "ko": "거래 PIN 설정/변경", "hi": "लेन-देन PIN सेट / बदलें", "tr": "İşlem PIN'i Ayarla / Değiştir", "nl": "Transactie PIN Instellen / Wijzigen", "pl": "Ustaw / Zmień PIN Transakcji"},
    "Recent transactions": {"es": "Transacciones recientes", "fr": "Transactions récentes", "de": "Letzte Transaktionen", "pt": "Transações recentes", "it": "Transazioni recenti", "ru": "Последние транзакции", "zh_HAns": "近期交易", "ar": "المعاملات الأخيرة", "ja": "最近の取引", "ko": "최근 거래", "hi": "हाल के लेन-देन", "tr": "Son İşlemler", "nl": "Recente Transacties", "pl": "Ostatnie Transakcje"},
    "Latest 5 transactions": {"es": "Últimas 5 transacciones", "fr": "5 dernières transactions", "de": "Letzte 5 Transaktionen", "pt": "Últimas 5 transações", "it": "Ultime 5 transazioni", "ru": "Последние 5 транзакций", "zh_HAns": "最近5笔交易", "ar": "آخر 5 معاملات", "ja": "最新5件の取引", "ko": "최근 5건의 거래", "hi": "नवीनतम 5 लेन-देन", "tr": "Son 5 İşlem", "nl": "Laatste 5 Transacties", "pl": "Ostatnie 5 Transakcji"},
    "No recent transactions": {"es": "Sin transacciones recientes", "fr": "Aucune transaction récente", "de": "Keine aktuellen Transaktionen", "pt": "Sem transações recentes", "it": "Nessuna transazione recente", "ru": "Нет последних транзакций", "zh_HAns": "暂无近期交易", "ar": "لا توجد معاملات حديثة", "ja": "最近の取引はありません", "ko": "최근 거래가 없습니다", "hi": "कोई हालिया लेन-देन नहीं", "tr": "Son işlem yok", "nl": "Geen recente transacties", "pl": "Brak ostatnich transakcji"},
    "View all": {"es": "Ver todo", "fr": "Voir tout", "de": "Alle anzeigen", "pt": "Ver tudo", "it": "Vedi tutto", "ru": "Просмотреть все", "zh_HAns": "查看全部", "ar": "عرض الكل", "ja": "すべて表示", "ko": "전체 보기", "hi": "सभी देखें", "tr": "Tümünü Gör", "nl": "Alles Bekijken", "pl": "Zobacz wszystkie"},
    "Card requests": {"es": "Solicitudes de tarjeta", "fr": "Demandes de carte", "de": "Kartenanfragen", "pt": "Pedidos de cartão", "it": "Richieste di carta", "ru": "Заявки на карту", "zh_HAns": "银行卡申请", "ar": "طلبات البطاقة", "ja": "カード申請", "ko": "카드 신청 내역", "hi": "कार्ड अनुरोध", "tr": "Kart Talepleri", "nl": "Kaartaanvragen", "pl": "Wnioski o Kartę"},
    "Latest requests": {"es": "Últimas solicitudes", "fr": "Dernières demandes", "de": "Letzte Anfragen", "pt": "Últimos pedidos", "it": "Ultime richieste", "ru": "Последние запросы", "zh_HAns": "最新申请", "ar": "أحدث الطلبات", "ja": "最新の申請", "ko": "최신 신청 내역", "hi": "नवीनतम अनुरोध", "tr": "Son Talepler", "nl": "Laatste Aanvragen", "pl": "Ostatnie Wnioski"},
    "Approved": {"es": "Aprobado", "fr": "Approuvé", "de": "Genehmigt", "pt": "Aprovado", "it": "Approvato", "ru": "Одобрено", "zh_HAns": "已批准", "ar": "موافق عليه", "ja": "承認済み", "ko": "승인됨", "hi": "स्वीकृत", "tr": "Onaylandı", "nl": "Goedgekeurd", "pl": "Zatwierdzone"},
    "Pending": {"es": "Pendiente", "fr": "En attente", "de": "Ausstehend", "pt": "Pendente", "it": "In attesa", "ru": "Ожидание", "zh_HAns": "待处理", "ar": "قيد الانتظار", "ja": "保留中", "ko": "대기 중", "hi": "लंबित", "tr": "Beklemede", "nl": "In Behandeling", "pl": "Oczekujące"},
    "Rejected": {"es": "Rechazado", "fr": "Rejeté", "de": "Abgelehnt", "pt": "Rejeitado", "it": "Rifiutato", "ru": "Отклонено", "zh_HAns": "已拒绝", "ar": "مرفوض", "ja": "拒否", "ko": "거절됨", "hi": "अस्वीकृत", "tr": "Reddedildi", "nl": "Afgewezen", "pl": "Odrzucone"},
    "No card requests": {"es": "Sin solicitudes de tarjeta", "fr": "Aucune demande de carte", "de": "Keine Kartenanfragen", "pt": "Sem pedidos de cartão", "it": "Nessuna richiesta di carta", "ru": "Нет заявок на карту", "zh_HAns": "暂无银行卡申请", "ar": "لا توجد طلبات بطاقة", "ja": "カード申請はありません", "ko": "카드 신청 내역이 없습니다", "hi": "कोई कार्ड अनुरोध नहीं", "tr": "Kart talebi yok", "nl": "Geen kaartaanvragen", "pl": "Brak wniosków o kartę"},
    "Messages": {"es": "Mensajes", "fr": "Messages", "de": "Nachrichten", "pt": "Mensagens", "it": "Messaggi", "ru": "Сообщения", "zh_HAns": "消息", "ar": "الرسائل", "ja": "メッセージ", "ko": "메시지", "hi": "संदेश", "tr": "Mesajlar", "nl": "Berichten", "pl": "Wiadomości"},
    "Recent conversation": {"es": "Conversación reciente", "fr": "Conversation récente", "de": "Letzte Unterhaltung", "pt": "Conversa recente", "it": "Conversazione recente", "ru": "Последний разговор", "zh_HAns": "最近对话", "ar": "المحادثة الأخيرة", "ja": "最近の会話", "ko": "최근 대화", "hi": "हाल की बातचीत", "tr": "Son Konuşma", "nl": "Recente Conversatie", "pl": "Ostatnia Rozmowa"},
    "No messages yet. Use Chat Support to contact us.": {"es": "Sin mensajes aún. Use el Chat de Soporte.", "fr": "Pas encore de messages. Utilisez le Chat de Support.", "de": "Noch keine Nachrichten. Nutzen Sie den Chat-Support.", "pt": "Sem mensagens ainda. Use o Suporte via Chat.", "it": "Nessun messaggio ancora. Usa la Chat di Supporto.", "ru": "Сообщений пока нет. Используйте чат поддержки.", "zh_HAns": "暂无消息，请使用在线客服联系我们。", "ar": "لا توجد رسائل بعد. استخدم دردشة الدعم.", "ja": "まだメッセージはありません。チャットサポートをご利用ください。", "ko": "메시지가 없습니다. 채팅 지원을 이용하세요.", "hi": "अभी तक कोई संदेश नहीं। चैट सहायता का उपयोग करें।", "tr": "Henüz mesaj yok. Sohbet Desteği'ni kullanın.", "nl": "Nog geen berichten. Gebruik Chat Ondersteuning.", "pl": "Brak wiadomości. Skorzystaj z czatu wsparcia."},
    "Open Chat": {"es": "Abrir Chat", "fr": "Ouvrir le Chat", "de": "Chat öffnen", "pt": "Abrir Chat", "it": "Apri Chat", "ru": "Открыть чат", "zh_HAns": "打开聊天", "ar": "فتح الدردشة", "ja": "チャットを開く", "ko": "채팅 열기", "hi": "चैट खोलें", "tr": "Sohbeti Aç", "nl": "Chat Openen", "pl": "Otwórz Czat"},
    "All Rights Reserved": {"es": "Todos los derechos reservados", "fr": "Tous droits réservés", "de": "Alle Rechte vorbehalten", "pt": "Todos os direitos reservados", "it": "Tutti i diritti riservati", "ru": "Все права защищены", "zh_HAns": "版权所有", "ar": "جميع الحقوق محفوظة", "ja": "全著作権所有", "ko": "모든 권리 보유", "hi": "सर्वाधिकार सुरक्षित", "tr": "Tüm Hakları Saklıdır", "nl": "Alle Rechten Voorbehouden", "pl": "Wszelkie Prawa Zastrzeżone"},
    "Home": {"es": "Inicio", "fr": "Accueil", "de": "Startseite", "pt": "Início", "it": "Home", "ru": "Главная", "zh_HAns": "首页", "ar": "الرئيسية", "ja": "ホーム", "ko": "홈", "hi": "होम", "tr": "Ana Sayfa", "nl": "Home", "pl": "Strona Główna"},
    "About": {"es": "Acerca de", "fr": "À propos", "de": "Über uns", "pt": "Sobre", "it": "Chi siamo", "ru": "О нас", "zh_HAns": "关于我们", "ar": "حول", "ja": "会社概要", "ko": "소개", "hi": "हमारे बारे में", "tr": "Hakkında", "nl": "Over ons", "pl": "O Nas"},
    "Services": {"es": "Servicios", "fr": "Services", "de": "Dienstleistungen", "pt": "Serviços", "it": "Servizi", "ru": "Услуги", "zh_HAns": "服务", "ar": "الخدمات", "ja": "サービス", "ko": "서비스", "hi": "सेवाएं", "tr": "Hizmetler", "nl": "Diensten", "pl": "Usługi"},
    "FAQs": {"es": "Preguntas frecuentes", "fr": "FAQ", "de": "FAQs", "pt": "Perguntas frequentes", "it": "FAQ", "ru": "Вопросы и ответы", "zh_HAns": "常见问题", "ar": "الأسئلة الشائعة", "ja": "よくある質問", "ko": "자주 묻는 질문", "hi": "सामान्य प्रश्न", "tr": "Sıkça Sorulan Sorular", "nl": "Veelgestelde Vragen", "pl": "Często Zadawane Pytania"},
    "Contact": {"es": "Contacto", "fr": "Contact", "de": "Kontakt", "pt": "Contato", "it": "Contatto", "ru": "Контакт", "zh_HAns": "联系我们", "ar": "اتصل بنا", "ja": "お問い合わせ", "ko": "연락처", "hi": "संपर्क", "tr": "İletişim", "nl": "Contact", "pl": "Kontakt"},
    "Deposit Funds": {"es": "Depositar Fondos", "fr": "Déposer des Fonds", "de": "Geld einzahlen", "pt": "Depositar Fundos", "it": "Depositare Fondi", "ru": "Внесение средств", "zh_HAns": "充值资金", "ar": "إيداع الأموال", "ja": "資金を入金", "ko": "자금 입금", "hi": "धन जमा करें", "tr": "Para Yatır", "nl": "Fondsen Storten", "pl": "Wpłać Środki"},
    "Current Balance": {"es": "Saldo Actual", "fr": "Solde Actuel", "de": "Aktueller Kontostand", "pt": "Saldo Atual", "it": "Saldo Attuale", "ru": "Текущий баланс", "zh_HAns": "当前余额", "ar": "الرصيد الحالي", "ja": "現在の残高", "ko": "현재 잔액", "hi": "वर्तमान शेष", "tr": "Mevcut Bakiye", "nl": "Huidig Saldo", "pl": "Aktualny Saldo"},
    "Payment Options": {"es": "Opciones de Pago", "fr": "Options de Paiement", "de": "Zahlungsoptionen", "pt": "Opções de Pagamento", "it": "Opzioni di Pagamento", "ru": "Способы оплаты", "zh_HAns": "支付方式", "ar": "خيارات الدفع", "ja": "支払い方法", "ko": "결제 옵션", "hi": "भुगतान विकल्प", "tr": "Ödeme Seçenekleri", "nl": "Betaalopties", "pl": "Opcje Płatności"},
    "Copy": {"es": "Copiar", "fr": "Copier", "de": "Kopieren", "pt": "Copiar", "it": "Copia", "ru": "Копировать", "zh_HAns": "复制", "ar": "نسخ", "ja": "コピー", "ko": "복사", "hi": "कॉपी करें", "tr": "Kopyala", "nl": "Kopiëren", "pl": "Kopiuj"},
    "Bitcoin (BTC):": {"es": "Bitcoin (BTC):", "fr": "Bitcoin (BTC):", "de": "Bitcoin (BTC):", "pt": "Bitcoin (BTC):", "it": "Bitcoin (BTC):", "ru": "Bitcoin (BTC):", "zh_HAns": "比特币 (BTC):", "ar": ":Bitcoin (BTC)", "ja": "ビットコイン (BTC):", "ko": "비트코인 (BTC):", "hi": "बिटकॉइन (BTC):", "tr": "Bitcoin (BTC):", "nl": "Bitcoin (BTC):", "pl": "Bitcoin (BTC):"},
    "Amount": {"es": "Cantidad", "fr": "Montant", "de": "Betrag", "pt": "Valor", "it": "Importo", "ru": "Сумма", "zh_HAns": "金额", "ar": "المبلغ", "ja": "金額", "ko": "금액", "hi": "राशि", "tr": "Tutar", "nl": "Bedrag", "pl": "Kwota"},
    "Enter amount to deposit": {"es": "Ingrese monto a depositar", "fr": "Entrez le montant à déposer", "de": "Einzahlungsbetrag eingeben", "pt": "Digite o valor a depositar", "it": "Inserisci l'importo da depositare", "ru": "Введите сумму для пополнения", "zh_HAns": "输入存款金额", "ar": "أدخل المبلغ المراد إيداعه", "ja": "入金金額を入力", "ko": "입금할 금액 입력", "hi": "जमा करने की राशि दर्ज करें", "tr": "Yatırılacak tutarı girin", "nl": "Voer het stortingsbedrag in", "pl": "Wprowadź kwotę do wpłacenia"},
    "Nothing to copy": {"es": "Nada que copiar", "fr": "Rien à copier", "de": "Nichts zum Kopieren", "pt": "Nada para copiar", "it": "Niente da copiare", "ru": "Нечего копировать", "zh_HAns": "没有可复制的内容", "ar": "لا شيء للنسخ", "ja": "コピーするものがありません", "ko": "복사할 내용이 없습니다", "hi": "कॉपी करने के लिए कुछ नहीं", "tr": "Kopyalanacak bir şey yok", "nl": "Niets te kopiëren", "pl": "Nic do skopiowania"},
    "Copied": {"es": "Copiado", "fr": "Copié", "de": "Kopiert", "pt": "Copiado", "it": "Copiato", "ru": "Скопировано", "zh_HAns": "已复制", "ar": "تم النسخ", "ja": "コピーしました", "ko": "복사됨", "hi": "कॉपी किया गया", "tr": "Kopyalandı", "nl": "Gekopieerd", "pl": "Skopiowano"},
    "Copy failed — please copy manually.": {"es": "Error al copiar — copie manualmente.", "fr": "Échec de la copie — copiez manuellement.", "de": "Kopieren fehlgeschlagen — bitte manuell kopieren.", "pt": "Falha ao copiar — copie manualmente.", "it": "Copia fallita — copia manualmente.", "ru": "Ошибка копирования — скопируйте вручную.", "zh_HAns": "复制失败，请手动复制。", "ar": "فشل النسخ — يرجى النسخ يدويًا.", "ja": "コピーに失敗しました — 手動でコピーしてください。", "ko": "복사 실패 — 수동으로 복사하세요.", "hi": "कॉपी विफल — कृपया मैन्युअल रूप से कॉपी करें।", "tr": "Kopyalama başarısız — lütfen manuel kopyalayın.", "nl": "Kopiëren mislukt — kopieer handmatig.", "pl": "Kopiowanie nie powiodło się — skopiuj ręcznie."},
    "Hello": {"es": "Hola", "fr": "Bonjour", "de": "Hallo", "pt": "Olá", "it": "Ciao", "ru": "Привет", "zh_HAns": "你好", "ar": "مرحبا", "ja": "こんにちは", "ko": "안녕하세요", "hi": "नमस्ते", "tr": "Merhaba", "nl": "Hallo", "pl": "Cześć"},
    "Internet Banking": {"es": "Banca en Línea", "fr": "Banque en Ligne", "de": "Online-Banking", "pt": "Banco Online", "it": "Banca Online", "ru": "Интернет-банкинг", "zh_HAns": "网上银行", "ar": "الخدمات المصرفية عبر الإنترنت", "ja": "インターネットバンキング", "ko": "인터넷 뱅킹", "hi": "इंटरनेट बैंकिंग", "tr": "İnternet Bankacılığı", "nl": "Internetbankieren", "pl": "Bankowość Internetowa"},
    "Personal Banking": {"es": "Banca Personal", "fr": "Banque Personnelle", "de": "Privatkundenbank", "pt": "Banco Pessoal", "it": "Banca Personale", "ru": "Персональный банкинг", "zh_HAns": "个人银行", "ar": "الخدمات المصرفية الشخصية", "ja": "個人バンキング", "ko": "개인 뱅킹", "hi": "व्यक्तिगत बैंकिंग", "tr": "Bireysel Bankacılık", "nl": "Persoonlijk Bankieren", "pl": "Bankowość Osobista"},
    "Bank with Us": {"es": "Banque con Nosotros", "fr": "Bancaire avec Nous", "de": "Bankieren bei uns", "pt": "Banque Conosco", "it": "Banca con Noi", "ru": "Банк с нами", "zh_HAns": "与我们一起银行", "ar": "تعامل معنا", "ja": "当行をご利用ください", "ko": "우리와 함께 뱅킹", "hi": "हमारे साथ बैंकिंग", "tr": "Bizimle Bankacılık", "nl": "Bankier bij Ons", "pl": "Bankuj z Nami"},
    "Register": {"es": "Registrarse", "fr": "S'inscrire", "de": "Registrieren", "pt": "Registrar", "it": "Registrati", "ru": "Зарегистрироваться", "zh_HAns": "注册", "ar": "تسجيل", "ja": "登録", "ko": "등록", "hi": "पंजीकरण", "tr": "Kayıt Ol", "nl": "Registreren", "pl": "Zarejestruj się"},
    "Login": {"es": "Iniciar sesión", "fr": "Connexion", "de": "Anmelden", "pt": "Entrar", "it": "Accedi", "ru": "Войти", "zh_HAns": "登录", "ar": "تسجيل الدخول", "ja": "ログイン", "ko": "로그인", "hi": "लॉग इन", "tr": "Giriş Yap", "nl": "Inloggen", "pl": "Zaloguj się"},
    "Corporate Banking": {"es": "Banca Corporativa", "fr": "Banque d'Entreprise", "de": "Firmenkundenbank", "pt": "Banco Corporativo", "it": "Banca Aziendale", "ru": "Корпоративный банкинг", "zh_HAns": "企业银行", "ar": "الخدمات المصرفية للشركات", "ja": "法人バンキング", "ko": "기업 뱅킹", "hi": "कॉर्पोरेट बैंकिंग", "tr": "Kurumsal Bankacılık", "nl": "Zakelijk Bankieren", "pl": "Bankowość Korporacyjna"},
    "Credit Card": {"es": "Tarjeta de Crédito", "fr": "Carte de Crédit", "de": "Kreditkarte", "pt": "Cartão de Crédito", "it": "Carta di Credito", "ru": "Кредитная карта", "zh_HAns": "信用卡", "ar": "بطاقة الائتمان", "ja": "クレジットカード", "ko": "신용카드", "hi": "क्रेडिट कार्ड", "tr": "Kredi Kartı", "nl": "Creditcard", "pl": "Karta Kredytowa"},
    "Business Banking": {"es": "Banca Empresarial", "fr": "Banque Professionnelle", "de": "Geschäftsbankgeschäft", "pt": "Banco Empresarial", "it": "Banca Aziendale", "ru": "Бизнес-банкинг", "zh_HAns": "商业银行", "ar": "الخدمات المصرفية للأعمال", "ja": "ビジネスバンキング", "ko": "비즈니스 뱅킹", "hi": "व्यवसाय बैंकिंग", "tr": "İşletme Bankacılığı", "nl": "Zakelijk Bankieren", "pl": "Bankowość Biznesowa"},
    "Wealth Management": {"es": "Gestión de Patrimonio", "fr": "Gestion de Patrimoine", "de": "Vermögensverwaltung", "pt": "Gestão de Patrimônio", "it": "Gestione Patrimoniale", "ru": "Управление активами", "zh_HAns": "财富管理", "ar": "إدارة الثروات", "ja": "資産運用", "ko": "자산 관리", "hi": "धन प्रबंधन", "tr": "Varlık Yönetimi", "nl": "Vermogensbeheer", "pl": "Zarządzanie Majątkiem"},
    "Privacy Policy": {"es": "Política de Privacidad", "fr": "Politique de Confidentialité", "de": "Datenschutzrichtlinie", "pt": "Política de Privacidade", "it": "Informativa sulla Privacy", "ru": "Политика конфиденциальности", "zh_HAns": "隐私政策", "ar": "سياسة الخصوصية", "ja": "プライバシーポリシー", "ko": "개인정보 처리방침", "hi": "गोपनीयता नीति", "tr": "Gizlilik Politikası", "nl": "Privacybeleid", "pl": "Polityka Prywatności"},
    "Welcome to": {"es": "Bienvenido a", "fr": "Bienvenue à", "de": "Willkommen bei", "pt": "Bem-vindo a", "it": "Benvenuto a", "ru": "Добро пожаловать в", "zh_HAns": "欢迎来到", "ar": "مرحبًا بك في", "ja": "ようこそ", "ko": "환영합니다", "hi": "स्वागत है", "tr": "Hoş Geldiniz", "nl": "Welkom bij", "pl": "Witamy w"},
    "Your trusted partner in secure, smart and convenient online banking. We're here to help you manage your finances with ease and confidence.": {"es": "Su socio de confianza en banca en línea segura, inteligente y conveniente.", "fr": "Votre partenaire de confiance pour une banque en ligne sécurisée et intelligente.", "de": "Ihr vertrauenswürdiger Partner für sicheres und intelligentes Online-Banking.", "pt": "Seu parceiro de confiança em banco online seguro e conveniente.", "it": "Il tuo partner di fiducia per un banking online sicuro e conveniente.", "ru": "Ваш надёжный партнёр в области безопасного онлайн-банкинга.", "zh_HAns": "您值得信赖的安全、智能、便捷的网上银行合作伙伴。", "ar": "شريكك الموثوق في الخدمات المصرفية الآمنة والذكية عبر الإنترنت.", "ja": "安全でスマートな便利なオンラインバンキングの信頼できるパートナー。", "ko": "안전하고 스마트한 온라인 뱅킹의 신뢰할 수 있는 파트너입니다.", "hi": "सुरक्षित, स्मार्ट और सुविधाजनक ऑनलाइन बैंकिंग में आपका विश्वसनीय भागीदार।", "tr": "Güvenli ve akıllı çevrimiçi bankacılıkta güvenilir ortağınız.", "nl": "Uw betrouwbare partner voor veilig en slim internetbankieren.", "pl": "Twój zaufany partner w bezpiecznej i inteligentnej bankowości online."},
    "Open Account": {"es": "Abrir Cuenta", "fr": "Ouvrir un Compte", "de": "Konto eröffnen", "pt": "Abrir Conta", "it": "Apri Conto", "ru": "Открыть счет", "zh_HAns": "开立账户", "ar": "فتح حساب", "ja": "口座開設", "ko": "계좌 개설", "hi": "खाता खोलें", "tr": "Hesap Aç", "nl": "Account Openen", "pl": "Otwórz Konto"},
    "Savings Account": {"es": "Cuenta de Ahorros", "fr": "Compte d'Épargne", "de": "Sparkonto", "pt": "Conta Poupança", "it": "Conto di Risparmio", "ru": "Сберегательный счет", "zh_HAns": "储蓄账户", "ar": "حساب التوفير", "ja": "普通預金口座", "ko": "저축 계좌", "hi": "बचत खाता", "tr": "Tasarruf Hesabı", "nl": "Spaarrekening", "pl": "Konto Oszczędnościowe"},
    "Banking Solutions": {"es": "Soluciones Bancarias", "fr": "Solutions Bancaires", "de": "Banklösungen", "pt": "Soluções Bancárias", "it": "Soluzioni Bancarie", "ru": "Банковские решения", "zh_HAns": "银行解决方案", "ar": "الحلول المصرفية", "ja": "バンキングソリューション", "ko": "뱅킹 솔루션", "hi": "बैंकिंग समाधान", "tr": "Bankacılık Çözümleri", "nl": "Bankoplossingen", "pl": "Rozwiązania Bankowe"},
    "Financial Solutions": {"es": "Soluciones Financieras", "fr": "Solutions Financières", "de": "Finanzlösungen", "pt": "Soluções Financeiras", "it": "Soluzioni Finanziarie", "ru": "Финансовые решения", "zh_HAns": "金融解决方案", "ar": "الحلول المالية", "ja": "金融ソリューション", "ko": "금융 솔루션", "hi": "वित्तीय समाधान", "tr": "Finansal Çözümler", "nl": "Financiële Oplossingen", "pl": "Rozwiązania Finansowe"},
    "Loan Solutions": {"es": "Soluciones de Préstamo", "fr": "Solutions de Prêt", "de": "Kreditlösungen", "pt": "Soluções de Empréstimo", "it": "Soluzioni di Prestito", "ru": "Кредитные решения", "zh_HAns": "贷款解决方案", "ar": "حلول القروض", "ja": "ローンソリューション", "ko": "대출 솔루션", "hi": "ऋण समाधान", "tr": "Kredi Çözümleri", "nl": "Leenoplossingen", "pl": "Rozwiązania Kredytowe"},
    "About Us": {"es": "Sobre Nosotros", "fr": "À Propos de Nous", "de": "Über Uns", "pt": "Sobre Nós", "it": "Chi Siamo", "ru": "О нас", "zh_HAns": "关于我们", "ar": "من نحن", "ja": "私たちについて", "ko": "우리에 대해", "hi": "हमारे बारे में", "tr": "Hakkımızda", "nl": "Over Ons", "pl": "O Nas"},
    "Our Mission": {"es": "Nuestra Misión", "fr": "Notre Mission", "de": "Unsere Mission", "pt": "Nossa Missão", "it": "La Nostra Missione", "ru": "Наша миссия", "zh_HAns": "我们的使命", "ar": "مهمتنا", "ja": "私たちの使命", "ko": "우리의 미션", "hi": "हमारा मिशन", "tr": "Misyonumuz", "nl": "Onze Missie", "pl": "Nasza Misja"},
    "Our Vision": {"es": "Nuestra Visión", "fr": "Notre Vision", "de": "Unsere Vision", "pt": "Nossa Visão", "it": "La Nostra Visione", "ru": "Наше видение", "zh_HAns": "我们的愿景", "ar": "رؤيتنا", "ja": "私たちのビジョン", "ko": "우리의 비전", "hi": "हमारी दृष्टि", "tr": "Vizyonumuz", "nl": "Onze Visie", "pl": "Nasza Wizja"},
    "Our Core Values": {"es": "Nuestros Valores Fundamentales", "fr": "Nos Valeurs Fondamentales", "de": "Unsere Kernwerte", "pt": "Nossos Valores Fundamentais", "it": "I Nostri Valori Fondamentali", "ru": "Наши основные ценности", "zh_HAns": "我们的核心价值观", "ar": "قيمنا الأساسية", "ja": "私たちの中核的価値観", "ko": "우리의 핵심 가치", "hi": "हमारे मूल मूल्य", "tr": "Temel Değerlerimiz", "nl": "Onze Kernwaarden", "pl": "Nasze Wartości Podstawowe"},
    "Our Services": {"es": "Nuestros Servicios", "fr": "Nos Services", "de": "Unsere Dienstleistungen", "pt": "Nossos Serviços", "it": "I Nostri Servizi", "ru": "Наши услуги", "zh_HAns": "我们的服务", "ar": "خدماتنا", "ja": "私たちのサービス", "ko": "우리의 서비스", "hi": "हमारी सेवाएं", "tr": "Hizmetlerimiz", "nl": "Onze Diensten", "pl": "Nasze Usługi"},
    "Testimonials": {"es": "Testimonios", "fr": "Témoignages", "de": "Testimonials", "pt": "Depoimentos", "it": "Testimonianze", "ru": "Отзывы", "zh_HAns": "用户评价", "ar": "الشهادات", "ja": "お客様の声", "ko": "고객 후기", "hi": "प्रशंसापत्र", "tr": "Referanslar", "nl": "Getuigenissen", "pl": "Referencje"},
    "Frequently Asked ": {"es": "Preguntas ", "fr": "Questions ", "de": "Häufig gestellte ", "pt": "Perguntas ", "it": "Domande ", "ru": "Часто задаваемые ", "zh_HAns": "常见", "ar": "الأسئلة المتداولة ", "ja": "よくある", "ko": "자주 묻는 ", "hi": "अक्सर पूछे जाने वाले ", "tr": "Sıkça Sorulan ", "nl": "Veelgestelde ", "pl": "Często Zadawane "},
    "Questions": {"es": "Preguntas", "fr": "Questions", "de": "Fragen", "pt": "Perguntas", "it": "Domande", "ru": "Вопросы", "zh_HAns": "问题", "ar": "الأسئلة", "ja": "質問", "ko": "질문", "hi": "प्रश्न", "tr": "Sorular", "nl": "Vragen", "pl": "Pytania"},
    "Get in touch": {"es": "Contáctenos", "fr": "Prenez contact", "de": "Kontakt aufnehmen", "pt": "Entre em contato", "it": "Contattaci", "ru": "Связаться с нами", "zh_HAns": "联系我们", "ar": "تواصل معنا", "ja": "お問い合わせ", "ko": "문의하기", "hi": "संपर्क करें", "tr": "Bize Ulaşın", "nl": "Neem Contact Op", "pl": "Skontaktuj się"},
    "Location:": {"es": "Ubicación:", "fr": "Localisation:", "de": "Standort:", "pt": "Localização:", "it": "Posizione:", "ru": "Местоположение:", "zh_HAns": "地址：", "ar": ":الموقع", "ja": "所在地：", "ko": "위치:", "hi": "स्थान:", "tr": "Konum:", "nl": "Locatie:", "pl": "Lokalizacja:"},
    "Email:": {"es": "Correo:", "fr": "Email:", "de": "E-Mail:", "pt": "E-mail:", "it": "Email:", "ru": "Email:", "zh_HAns": "邮箱：", "ar": ":البريد الإلكتروني", "ja": "メール：", "ko": "이메일:", "hi": "ईमेल:", "tr": "E-posta:", "nl": "E-mail:", "pl": "E-mail:"},
    "Call:": {"es": "Teléfono:", "fr": "Téléphone:", "de": "Telefon:", "pt": "Telefone:", "it": "Telefono:", "ru": "Телефон:", "zh_HAns": "电话：", "ar": ":الهاتف", "ja": "電話：", "ko": "전화:", "hi": "फोन:", "tr": "Telefon:", "nl": "Bellen:", "pl": "Zadzwoń:"},
    "Your Name": {"es": "Tu Nombre", "fr": "Votre Nom", "de": "Ihr Name", "pt": "Seu Nome", "it": "Il Tuo Nome", "ru": "Ваше имя", "zh_HAns": "您的姓名", "ar": "اسمك", "ja": "お名前", "ko": "이름", "hi": "आपका नाम", "tr": "Adınız", "nl": "Uw Naam", "pl": "Twoje Imię"},
    "Your Email": {"es": "Tu Correo", "fr": "Votre Email", "de": "Ihre E-Mail", "pt": "Seu E-mail", "it": "La Tua Email", "ru": "Ваш email", "zh_HAns": "您的邮箱", "ar": "بريدك الإلكتروني", "ja": "メールアドレス", "ko": "이메일", "hi": "आपका ईमेल", "tr": "E-postanız", "nl": "Uw E-mail", "pl": "Twój E-mail"},
    "Subject": {"es": "Asunto", "fr": "Sujet", "de": "Betreff", "pt": "Assunto", "it": "Oggetto", "ru": "Тема", "zh_HAns": "主题", "ar": "الموضوع", "ja": "件名", "ko": "제목", "hi": "विषय", "tr": "Konu", "nl": "Onderwerp", "pl": "Temat"},
    "Message": {"es": "Mensaje", "fr": "Message", "de": "Nachricht", "pt": "Mensagem", "it": "Messaggio", "ru": "Сообщение", "zh_HAns": "消息", "ar": "رسالة", "ja": "メッセージ", "ko": "메시지", "hi": "संदेश", "tr": "Mesaj", "nl": "Bericht", "pl": "Wiadomość"},
    "Send Message": {"es": "Enviar Mensaje", "fr": "Envoyer le Message", "de": "Nachricht senden", "pt": "Enviar Mensagem", "it": "Invia Messaggio", "ru": "Отправить сообщение", "zh_HAns": "发送消息", "ar": "أرسل رسالة", "ja": "メッセージを送る", "ko": "메시지 보내기", "hi": "संदेश भेजें", "tr": "Mesaj Gönder", "nl": "Bericht Versturen", "pl": "Wyślij Wiadomość"},
    "Loading": {"es": "Cargando", "fr": "Chargement", "de": "Laden", "pt": "Carregando", "it": "Caricamento", "ru": "Загрузка", "zh_HAns": "加载中", "ar": "جار التحميل", "ja": "読み込み中", "ko": "로딩 중", "hi": "लोड हो रहा है", "tr": "Yükleniyor", "nl": "Laden", "pl": "Ładowanie"},
    "Your message has been sent. Thank you!": {"es": "Su mensaje fue enviado. ¡Gracias!", "fr": "Votre message a été envoyé. Merci!", "de": "Ihre Nachricht wurde gesendet. Danke!", "pt": "Sua mensagem foi enviada. Obrigado!", "it": "Il tuo messaggio è stato inviato. Grazie!", "ru": "Ваше сообщение отправлено. Спасибо!", "zh_HAns": "您的消息已发送，谢谢！", "ar": "تم إرسال رسالتك. شكرًا!", "ja": "メッセージが送信されました。ありがとうございます！", "ko": "메시지가 전송되었습니다. 감사합니다!", "hi": "आपका संदेश भेजा गया। धन्यवाद!", "tr": "Mesajınız gönderildi. Teşekkürler!", "nl": "Uw bericht is verzonden. Bedankt!", "pl": "Twoja wiadomość została wysłana. Dziękujemy!"},
    "Phone:": {"es": "Teléfono:", "fr": "Téléphone:", "de": "Telefon:", "pt": "Telefone:", "it": "Telefono:", "ru": "Телефон:", "zh_HAns": "电话：", "ar": ":الهاتف", "ja": "電話：", "ko": "전화:", "hi": "फोन:", "tr": "Telefon:", "nl": "Telefoon:", "pl": "Telefon:"},
    "Useful Links": {"es": "Enlaces Útiles", "fr": "Liens Utiles", "de": "Nützliche Links", "pt": "Links Úteis", "it": "Link Utili", "ru": "Полезные ссылки", "zh_HAns": "有用链接", "ar": "روابط مفيدة", "ja": "便利なリンク", "ko": "유용한 링크", "hi": "उपयोगी लिंक", "tr": "Yararlı Bağlantılar", "nl": "Nuttige Links", "pl": "Przydatne Linki"},
    "About us": {"es": "Sobre nosotros", "fr": "À propos de nous", "de": "Über uns", "pt": "Sobre nós", "it": "Chi siamo", "ru": "О нас", "zh_HAns": "关于我们", "ar": "من نحن", "ja": "私たちについて", "ko": "우리에 대해", "hi": "हमारे बारे में", "tr": "Hakkımızda", "nl": "Over ons", "pl": "O nas"},
    "Open an Account": {"es": "Abrir una Cuenta", "fr": "Ouvrir un Compte", "de": "Konto eröffnen", "pt": "Abrir uma Conta", "it": "Apri un Conto", "ru": "Открыть счет", "zh_HAns": "开立账户", "ar": "فتح حساب", "ja": "口座を開く", "ko": "계좌 개설", "hi": "खाता खोलें", "tr": "Hesap Aç", "nl": "Een Account Openen", "pl": "Otwórz Konto"},
    "Login to TrustBank.Plc": {"es": "Iniciar sesión en TrustBank.Plc", "fr": "Connexion à TrustBank.Plc", "de": "Bei TrustBank.Plc anmelden", "pt": "Entrar no TrustBank.Plc", "it": "Accedi a TrustBank.Plc", "ru": "Войти в TrustBank.Plc", "zh_HAns": "登录 TrustBank.Plc", "ar": "تسجيل الدخول إلى TrustBank.Plc", "ja": "TrustBank.Plcにログイン", "ko": "TrustBank.Plc 로그인", "hi": "TrustBank.Plc में लॉग इन करें", "tr": "TrustBank.Plc'ye Giriş Yap", "nl": "Inloggen bij TrustBank.Plc", "pl": "Zaloguj się do TrustBank.Plc"},
    "Username": {"es": "Nombre de usuario", "fr": "Nom d'utilisateur", "de": "Benutzername", "pt": "Nome de usuário", "it": "Nome utente", "ru": "Имя пользователя", "zh_HAns": "用户名", "ar": "اسم المستخدم", "ja": "ユーザー名", "ko": "사용자 이름", "hi": "उपयोगकर्ता नाम", "tr": "Kullanıcı Adı", "nl": "Gebruikersnaam", "pl": "Nazwa Użytkownika"},
    "Please enter your username.": {"es": "Por favor ingrese su nombre de usuario.", "fr": "Veuillez entrer votre nom d'utilisateur.", "de": "Bitte geben Sie Ihren Benutzernamen ein.", "pt": "Por favor insira seu nome de usuário.", "it": "Si prega di inserire il nome utente.", "ru": "Пожалуйста, введите имя пользователя.", "zh_HAns": "请输入您的用户名。", "ar": "الرجاء إدخال اسم المستخدم.", "ja": "ユーザー名を入力してください。", "ko": "사용자 이름을 입력하세요.", "hi": "कृपया अपना उपयोगकर्ता नाम दर्ज करें।", "tr": "Lütfen kullanıcı adınızı girin.", "nl": "Voer uw gebruikersnaam in.", "pl": "Proszę podać nazwę użytkownika."},
    "Password": {"es": "Contraseña", "fr": "Mot de passe", "de": "Passwort", "pt": "Senha", "it": "Password", "ru": "Пароль", "zh_HAns": "密码", "ar": "كلمة المرور", "ja": "パスワード", "ko": "비밀번호", "hi": "पासवर्ड", "tr": "Şifre", "nl": "Wachtwoord", "pl": "Hasło"},
    "Please enter your password.": {"es": "Por favor ingrese su contraseña.", "fr": "Veuillez entrer votre mot de passe.", "de": "Bitte geben Sie Ihr Passwort ein.", "pt": "Por favor insira sua senha.", "it": "Si prega di inserire la password.", "ru": "Пожалуйста, введите пароль.", "zh_HAns": "请输入您的密码。", "ar": "الرجاء إدخال كلمة المرور.", "ja": "パスワードを入力してください。", "ko": "비밀번호를 입력하세요.", "hi": "कृपया अपना पासवर्ड दर्ज करें।", "tr": "Lütfen şifrenizi girin.", "nl": "Voer uw wachtwoord in.", "pl": "Proszę podać hasło."},
    "Don't have an account?": {"es": "¿No tienes una cuenta?", "fr": "Vous n'avez pas de compte?", "de": "Kein Konto?", "pt": "Não tem uma conta?", "it": "Non hai un account?", "ru": "Нет аккаунта?", "zh_HAns": "没有账户？", "ar": "ليس لديك حساب؟", "ja": "アカウントをお持ちでないですか？", "ko": "계정이 없으신가요?", "hi": "खाता नहीं है?", "tr": "Hesabınız yok mu?", "nl": "Geen account?", "pl": "Nie masz konta?"},
    "Chat with Support": {"es": "Chatear con Soporte", "fr": "Chatter avec le Support", "de": "Mit dem Support chatten", "pt": "Conversar com Suporte", "it": "Chatta con il Supporto", "ru": "Чат с поддержкой", "zh_HAns": "与客服聊天", "ar": "الدردشة مع الدعم", "ja": "サポートとチャット", "ko": "지원팀과 채팅", "hi": "सहायता से चैट करें", "tr": "Destekle Sohbet Et", "nl": "Chat met Ondersteuning", "pl": "Czat z Pomocą Techniczną"},
    "Back to Account Dashboard": {"es": "Volver al Panel de Cuenta", "fr": "Retour au Tableau de Bord", "de": "Zurück zum Konto-Dashboard", "pt": "Voltar ao Painel da Conta", "it": "Torna alla Dashboard dell'Account", "ru": "Вернуться в личный кабинет", "zh_HAns": "返回账户控制台", "ar": "العودة إلى لوحة الحساب", "ja": "アカウントダッシュボードに戻る", "ko": "계정 대시보드로 돌아가기", "hi": "खाता डैशबोर्ड पर वापस जाएं", "tr": "Hesap Paneline Dön", "nl": "Terug naar Account Dashboard", "pl": "Wróć do Panelu Konta"},
    "No messages yet. Start the conversation below!": {"es": "Sin mensajes aún. ¡Comience la conversación!", "fr": "Pas encore de messages. Commencez la conversation!", "de": "Noch keine Nachrichten. Starten Sie das Gespräch!", "pt": "Sem mensagens ainda. Inicie a conversa!", "it": "Nessun messaggio ancora. Inizia la conversazione!", "ru": "Сообщений пока нет. Начните разговор!", "zh_HAns": "暂无消息，请开始对话！", "ar": "لا توجد رسائل بعد. ابدأ المحادثة!", "ja": "まだメッセージはありません。会話を始めましょう！", "ko": "메시지가 없습니다. 대화를 시작하세요!", "hi": "अभी तक कोई संदेश नहीं। नीचे बातचीत शुरू करें!", "tr": "Henüz mesaj yok. Konuşmayı başlatın!", "nl": "Nog geen berichten. Begin het gesprek!", "pl": "Brak wiadomości. Rozpocznij rozmowę!"},
    "Type your message...": {"es": "Escribe tu mensaje...", "fr": "Tapez votre message...", "de": "Nachricht eingeben...", "pt": "Digite sua mensagem...", "it": "Scrivi il tuo messaggio...", "ru": "Введите сообщение...", "zh_HAns": "输入您的消息...", "ar": "اكتب رسالتك...", "ja": "メッセージを入力...", "ko": "메시지를 입력하세요...", "hi": "अपना संदेश लिखें...", "tr": "Mesajınızı yazın...", "nl": "Typ uw bericht...", "pl": "Wpisz wiadomość..."},
    "New message from admin": {"es": "Nuevo mensaje del administrador", "fr": "Nouveau message de l'administrateur", "de": "Neue Nachricht vom Administrator", "pt": "Nova mensagem do administrador", "it": "Nuovo messaggio dall'amministratore", "ru": "Новое сообщение от администратора", "zh_HAns": "管理员的新消息", "ar": "رسالة جديدة من المسؤول", "ja": "管理者からの新しいメッセージ", "ko": "관리자로부터 새 메시지", "hi": "व्यवस्थापक से नया संदेश", "tr": "Yöneticiden yeni mesaj", "nl": "Nieuw bericht van beheerder", "pl": "Nowa wiadomość od administratora"},
    "Privacy Policy for TrustBank.Plc": {"es": "Política de Privacidad de TrustBank.Plc", "fr": "Politique de Confidentialité de TrustBank.Plc", "de": "Datenschutzrichtlinie von TrustBank.Plc", "pt": "Política de Privacidade da TrustBank.Plc", "it": "Informativa sulla Privacy di TrustBank.Plc", "ru": "Политика конфиденциальности TrustBank.Plc", "zh_HAns": "TrustBank.Plc隐私政策", "ar": "سياسة خصوصية TrustBank.Plc", "ja": "TrustBank.Plcのプライバシーポリシー", "ko": "TrustBank.Plc 개인정보 처리방침", "hi": "TrustBank.Plc की गोपनीयता नीति", "tr": "TrustBank.Plc Gizlilik Politikası", "nl": "Privacybeleid van TrustBank.Plc", "pl": "Polityka Prywatności TrustBank.Plc"},
    "Consent": {"es": "Consentimiento", "fr": "Consentement", "de": "Zustimmung", "pt": "Consentimento", "it": "Consenso", "ru": "Согласие", "zh_HAns": "同意", "ar": "الموافقة", "ja": "同意", "ko": "동의", "hi": "सहमति", "tr": "Onay", "nl": "Toestemming", "pl": "Zgoda"},
    "Information we collect": {"es": "Información que recopilamos", "fr": "Informations que nous collectons", "de": "Informationen, die wir sammeln", "pt": "Informações que coletamos", "it": "Informazioni che raccogliamo", "ru": "Собираемая нами информация", "zh_HAns": "我们收集的信息", "ar": "المعلومات التي نجمعها", "ja": "収集する情報", "ko": "수집하는 정보", "hi": "हम जो जानकारी एकत्र करते हैं", "tr": "Topladığımız Bilgiler", "nl": "Informatie die we verzamelen", "pl": "Informacje, które zbieramy"},
    "How we use your information": {"es": "Cómo usamos su información", "fr": "Comment nous utilisons vos informations", "de": "Wie wir Ihre Informationen verwenden", "pt": "Como usamos suas informações", "it": "Come utilizziamo le tue informazioni", "ru": "Как мы используем вашу информацию", "zh_HAns": "我们如何使用您的信息", "ar": "كيف نستخدم معلوماتك", "ja": "情報の使用方法", "ko": "정보 사용 방법", "hi": "हम आपकी जानकारी का उपयोग कैसे करते हैं", "tr": "Bilgilerinizi Nasıl Kullanıyoruz", "nl": "Hoe wij uw informatie gebruiken", "pl": "Jak używamy Twoich informacji"},
    "Log Files": {"es": "Archivos de Registro", "fr": "Fichiers de Journal", "de": "Log-Dateien", "pt": "Arquivos de Log", "it": "File di Log", "ru": "Лог-файлы", "zh_HAns": "日志文件", "ar": "ملفات السجل", "ja": "ログファイル", "ko": "로그 파일", "hi": "लॉग फ़ाइलें", "tr": "Günlük Dosyaları", "nl": "Logbestanden", "pl": "Pliki Dziennika"},
    "Cookies and Web Beacons": {"es": "Cookies y Balizas Web", "fr": "Cookies et Balises Web", "de": "Cookies und Web-Beacons", "pt": "Cookies e Web Beacons", "it": "Cookie e Web Beacon", "ru": "Файлы cookie и веб-маяки", "zh_HAns": "Cookie和网络信标", "ar": "ملفات تعريف الارتباط والإشارات", "ja": "CookieとWebビーコン", "ko": "쿠키 및 웹 비콘", "hi": "कुकीज़ और वेब बीकन", "tr": "Çerezler ve Web İşaretçileri", "nl": "Cookies en Webbakens", "pl": "Pliki Cookie i Sygnalizatory Internetowe"},
    "Third Party Privacy Policies": {"es": "Políticas de Privacidad de Terceros", "fr": "Politiques de Confidentialité des Tiers", "de": "Datenschutzrichtlinien Dritter", "pt": "Políticas de Privacidade de Terceiros", "it": "Politiche sulla Privacy di Terze Parti", "ru": "Политики конфиденциальности третьих сторон", "zh_HAns": "第三方隐私政策", "ar": "سياسات خصوصية الأطراف الثالثة", "ja": "第三者プライバシーポリシー", "ko": "제3자 개인정보 처리방침", "hi": "तृतीय पक्ष गोपनीयता नीतियां", "tr": "Üçüncü Taraf Gizlilik Politikaları", "nl": "Privacybeleid van Derden", "pl": "Polityki Prywatności Stron Trzecich"},
    "GDPR Data Protection Rights": {"es": "Derechos de Protección de Datos GDPR", "fr": "Droits de Protection des Données RGPD", "de": "DSGVO-Datenschutzrechte", "pt": "Direitos de Proteção de Dados RGPD", "it": "Diritti di Protezione dei Dati GDPR", "ru": "Права на защиту данных по GDPR", "zh_HAns": "GDPR数据保护权利", "ar": "حقوق حماية البيانات بموجب GDPR", "ja": "GDPRデータ保護権", "ko": "GDPR 데이터 보호 권리", "hi": "GDPR डेटा सुरक्षा अधिकार", "tr": "GDPR Veri Koruma Hakları", "nl": "AVG Gegevensbeschermingsrechten", "pl": "Prawa Ochrony Danych RODO"},
    "Children's Information": {"es": "Información sobre Niños", "fr": "Informations sur les Enfants", "de": "Informationen für Kinder", "pt": "Informações sobre Crianças", "it": "Informazioni sui Bambini", "ru": "Информация о детях", "zh_HAns": "儿童信息", "ar": "معلومات الأطفال", "ja": "子供の情報", "ko": "아동 정보", "hi": "बच्चों की जानकारी", "tr": "Çocuklara Ait Bilgiler", "nl": "Informatie over Kinderen", "pl": "Informacje o Dzieciach"},
    "Create an Account": {"es": "Crear una Cuenta", "fr": "Créer un Compte", "de": "Konto erstellen", "pt": "Criar uma Conta", "it": "Crea un Account", "ru": "Создать аккаунт", "zh_HAns": "创建账户", "ar": "إنشاء حساب", "ja": "アカウントを作成", "ko": "계정 만들기", "hi": "खाता बनाएं", "tr": "Hesap Oluştur", "nl": "Account Aanmaken", "pl": "Utwórz Konto"},
    "Join TrustBank.Plc and start managing your finances with ease.": {"es": "Únase a TrustBank.Plc y gestione sus finanzas con facilidad.", "fr": "Rejoignez TrustBank.Plc et gérez vos finances facilement.", "de": "Treten Sie TrustBank.Plc bei und verwalten Sie Ihre Finanzen.", "pt": "Junte-se à TrustBank.Plc e gerencie suas finanças.", "it": "Unisciti a TrustBank.Plc e gestisci le tue finanze.", "ru": "Присоединитесь к TrustBank.Plc и управляйте своими финансами.", "zh_HAns": "加入TrustBank.Plc，轻松管理您的财务。", "ar": "انضم إلى TrustBank.Plc وابدأ إدارة شؤونك المالية بسهولة.", "ja": "TrustBank.Plcに参加して財務を簡単に管理しましょう。", "ko": "TrustBank.Plc에 가입하여 재정을 쉽게 관리하세요.", "hi": "TrustBank.Plc से जुड़ें और अपने वित्त को आसानी से प्रबंधित करें।", "tr": "TrustBank.Plc'ye katılın ve finanslarınızı kolayca yönetin.", "nl": "Word lid van TrustBank.Plc en beheer uw financiën gemakkelijk.", "pl": "Dołącz do TrustBank.Plc i łatwo zarządzaj swoimi finansami."},
    "Personal Information": {"es": "Información Personal", "fr": "Informations Personnelles", "de": "Persönliche Informationen", "pt": "Informações Pessoais", "it": "Informazioni Personali", "ru": "Личная информация", "zh_HAns": "个人信息", "ar": "المعلومات الشخصية", "ja": "個人情報", "ko": "개인 정보", "hi": "व्यक्तिगत जानकारी", "tr": "Kişisel Bilgiler", "nl": "Persoonlijke Informatie", "pl": "Dane Osobowe"},
    "Address Information": {"es": "Información de Dirección", "fr": "Informations d'Adresse", "de": "Adressinformationen", "pt": "Informações de Endereço", "it": "Informazioni sull'Indirizzo", "ru": "Адресная информация", "zh_HAns": "地址信息", "ar": "معلومات العنوان", "ja": "住所情報", "ko": "주소 정보", "hi": "पता जानकारी", "tr": "Adres Bilgileri", "nl": "Adresgegevens", "pl": "Informacje Adresowe"},
    "Verification Information": {"es": "Información de Verificación", "fr": "Informations de Vérification", "de": "Verifizierungsinformationen", "pt": "Informações de Verificação", "it": "Informazioni di Verifica", "ru": "Данные для верификации", "zh_HAns": "验证信息", "ar": "معلومات التحقق", "ja": "本人確認情報", "ko": "인증 정보", "hi": "सत्यापन जानकारी", "tr": "Doğrulama Bilgileri", "nl": "Verificatie-informatie", "pl": "Informacje Weryfikacyjne"},
    "Password Information": {"es": "Información de Contraseña", "fr": "Informations de Mot de Passe", "de": "Passwortinformationen", "pt": "Informações de Senha", "it": "Informazioni sulla Password", "ru": "Информация о пароле", "zh_HAns": "密码信息", "ar": "معلومات كلمة المرور", "ja": "パスワード情報", "ko": "비밀번호 정보", "hi": "पासवर्ड जानकारी", "tr": "Şifre Bilgileri", "nl": "Wachtwoordinformatie", "pl": "Informacje o Haśle"},
    "Total Credit": {"es": "Crédito Total", "fr": "Crédit Total", "de": "Gesamtguthaben", "pt": "Crédito Total", "it": "Credito Totale", "ru": "Общий кредит", "zh_HAns": "总收入", "ar": "إجمالي الائتمان", "ja": "総入金", "ko": "총 입금액", "hi": "कुल क्रेडिट", "tr": "Toplam Kredi", "nl": "Totaal Krediet", "pl": "Całkowity Kredyt"},
    "Total Debit": {"es": "Débito Total", "fr": "Débit Total", "de": "Gesamtbelastung", "pt": "Débito Total", "it": "Addebito Totale", "ru": "Общий дебет", "zh_HAns": "总支出", "ar": "إجمالي المدين", "ja": "総出金", "ko": "총 출금액", "hi": "कुल डेबिट", "tr": "Toplam Borç", "nl": "Totaal Debet", "pl": "Całkowity Debet"},
    "Transaction History": {"es": "Historial de Transacciones", "fr": "Historique des Transactions", "de": "Transaktionsverlauf", "pt": "Histórico de Transações", "it": "Cronologia delle Transazioni", "ru": "История транзакций", "zh_HAns": "交易历史", "ar": "تاريخ المعاملات", "ja": "取引履歴", "ko": "거래 내역", "hi": "लेन-देन इतिहास", "tr": "İşlem Geçmişi", "nl": "Transactiegeschiedenis", "pl": "Historia Transakcji"},
    "No transactions found.": {"es": "No se encontraron transacciones.", "fr": "Aucune transaction trouvée.", "de": "Keine Transaktionen gefunden.", "pt": "Nenhuma transação encontrada.", "it": "Nessuna transazione trovata.", "ru": "Транзакции не найдены.", "zh_HAns": "未找到交易记录。", "ar": "لم يتم العثور على معاملات.", "ja": "取引が見つかりません。", "ko": "거래 내역이 없습니다.", "hi": "कोई लेन-देन नहीं मिला।", "tr": "İşlem bulunamadı.", "nl": "Geen transacties gevonden.", "pl": "Nie znaleziono transakcji."},
    "Transfer Money": {"es": "Transferir Dinero", "fr": "Transférer de l'Argent", "de": "Geld überweisen", "pt": "Transferir Dinheiro", "it": "Trasferisci Denaro", "ru": "Перевести деньги", "zh_HAns": "转账", "ar": "تحويل الأموال", "ja": "送金", "ko": "송금", "hi": "पैसे ट्रांसफर करें", "tr": "Para Transferi", "nl": "Geld Overmaken", "pl": "Przelej Pieniądze"},
    "Available Balance:": {"es": "Saldo Disponible:", "fr": "Solde Disponible:", "de": "Verfügbares Guthaben:", "pt": "Saldo Disponível:", "it": "Saldo Disponibile:", "ru": "Доступный баланс:", "zh_HAns": "可用余额：", "ar": "الرصيد المتاح:", "ja": "利用可能残高：", "ko": "사용 가능 잔액:", "hi": "उपलब्ध शेष राशि:", "tr": "Kullanılabilir Bakiye:", "nl": "Beschikbaar Saldo:", "pl": "Dostępne Saldo:"},
    "Recipient Account Number": {"es": "Número de Cuenta del Destinatario", "fr": "Numéro de Compte du Destinataire", "de": "Empfängerkontonummer", "pt": "Número de Conta do Destinatário", "it": "Numero di Conto del Destinatario", "ru": "Номер счета получателя", "zh_HAns": "收款人账户号码", "ar": "رقم حساب المستلم", "ja": "受取人口座番号", "ko": "수신인 계좌 번호", "hi": "प्राप्तकर्ता खाता संख्या", "tr": "Alıcı Hesap Numarası", "nl": "Rekeningnummer Ontvanger", "pl": "Numer Konta Odbiorcy"},
    "Recipient Name": {"es": "Nombre del Destinatario", "fr": "Nom du Destinataire", "de": "Name des Empfängers", "pt": "Nome do Destinatário", "it": "Nome del Destinatario", "ru": "Имя получателя", "zh_HAns": "收款人姓名", "ar": "اسم المستلم", "ja": "受取人名", "ko": "수신인 이름", "hi": "प्राप्तकर्ता का नाम", "tr": "Alıcı Adı", "nl": "Naam Ontvanger", "pl": "Imię Odbiorcy"},
    "Account found": {"es": "Cuenta encontrada", "fr": "Compte trouvé", "de": "Konto gefunden", "pt": "Conta encontrada", "it": "Account trovato", "ru": "Счет найден", "zh_HAns": "找到账户", "ar": "تم العثور على الحساب", "ja": "口座が見つかりました", "ko": "계좌 발견", "hi": "खाता मिला", "tr": "Hesap bulundu", "nl": "Account gevonden", "pl": "Konto znalezione"},
    "Description (optional)": {"es": "Descripción (opcional)", "fr": "Description (optionnel)", "de": "Beschreibung (optional)", "pt": "Descrição (opcional)", "it": "Descrizione (opzionale)", "ru": "Описание (необязательно)", "zh_HAns": "备注（可选）", "ar": "الوصف (اختياري)", "ja": "説明（任意）", "ko": "설명 (선택사항)", "hi": "विवरण (वैकल्पिक)", "tr": "Açıklama (isteğe bağlı)", "nl": "Beschrijving (optioneel)", "pl": "Opis (opcjonalny)"},
    "Transaction PIN": {"es": "PIN de Transacción", "fr": "PIN de Transaction", "de": "Transaktions-PIN", "pt": "PIN de Transação", "it": "PIN Transazione", "ru": "PIN транзакции", "zh_HAns": "交易密码", "ar": "رمز المعاملة", "ja": "取引PIN", "ko": "거래 PIN", "hi": "लेन-देन PIN", "tr": "İşlem PIN'i", "nl": "Transactie PIN", "pl": "PIN Transakcji"},
    "Enter your PIN": {"es": "Ingrese su PIN", "fr": "Entrez votre PIN", "de": "PIN eingeben", "pt": "Digite seu PIN", "it": "Inserisci il tuo PIN", "ru": "Введите PIN", "zh_HAns": "输入您的密码", "ar": "أدخل رمز PIN الخاص بك", "ja": "PINを入力", "ko": "PIN 입력", "hi": "अपना PIN दर्ज करें", "tr": "PIN'inizi girin", "nl": "Voer uw PIN in", "pl": "Wprowadź PIN"},
    "Set Transaction PIN": {"es": "Establecer PIN de Transacción", "fr": "Définir le PIN de Transaction", "de": "Transaktions-PIN festlegen", "pt": "Definir PIN de Transação", "it": "Imposta PIN Transazione", "ru": "Установить PIN транзакции", "zh_HAns": "设置交易密码", "ar": "تعيين رمز المعاملة", "ja": "取引PINを設定", "ko": "거래 PIN 설정", "hi": "लेन-देन PIN सेट करें", "tr": "İşlem PIN'ini Ayarla", "nl": "Transactie PIN Instellen", "pl": "Ustaw PIN Transakcji"},
    "Set Your Transaction PIN": {"es": "Establezca su PIN de Transacción", "fr": "Définissez votre PIN de Transaction", "de": "Legen Sie Ihren Transaktions-PIN fest", "pt": "Defina seu PIN de Transação", "it": "Imposta il tuo PIN di Transazione", "ru": "Установите PIN транзакции", "zh_HAns": "设置您的交易密码", "ar": "قم بتعيين رمز معاملتك", "ja": "取引PINを設定してください", "ko": "거래 PIN을 설정하세요", "hi": "अपना लेन-देन PIN सेट करें", "tr": "İşlem PIN'inizi Ayarlayın", "nl": "Stel uw Transactie PIN in", "pl": "Ustaw swój PIN Transakcji"},
    "Top Up Balance": {"es": "Recargar Saldo", "fr": "Recharger le Solde", "de": "Guthaben aufladen", "pt": "Recarregar Saldo", "it": "Ricarica Saldo", "ru": "Пополнить баланс", "zh_HAns": "充值余额", "ar": "شحن الرصيد", "ja": "残高をチャージ", "ko": "잔액 충전", "hi": "बैलेंस टॉप अप करें", "tr": "Bakiye Yükle", "nl": "Saldo Opwaarderen", "pl": "Doładuj Saldo"},
    "Top Up": {"es": "Recargar", "fr": "Recharger", "de": "Aufladen", "pt": "Recarregar", "it": "Ricarica", "ru": "Пополнить", "zh_HAns": "充值", "ar": "شحن", "ja": "チャージ", "ko": "충전", "hi": "टॉप अप", "tr": "Yükle", "nl": "Opwaarderen", "pl": "Doładuj"},
    "Enter amount to top up": {"es": "Ingrese monto a recargar", "fr": "Entrez le montant à recharger", "de": "Aufladebetrag eingeben", "pt": "Digite o valor a recarregar", "it": "Inserisci l'importo da ricaricare", "ru": "Введите сумму пополнения", "zh_HAns": "输入充值金额", "ar": "أدخل مبلغ الشحن", "ja": "チャージ金額を入力", "ko": "충전할 금액 입력", "hi": "टॉप अप करने की राशि दर्ज करें", "tr": "Yüklenecek tutarı girin", "nl": "Voer het opwaardeer bedrag in", "pl": "Wprowadź kwotę doładowania"},
    "Business Consulting": {"es": "Consultoría Empresarial", "fr": "Conseil aux Entreprises", "de": "Unternehmensberatung", "pt": "Consultoria Empresarial", "it": "Consulenza Aziendale", "ru": "Бизнес-консалтинг", "zh_HAns": "商业咨询", "ar": "استشارات الأعمال", "ja": "ビジネスコンサルティング", "ko": "비즈니스 컨설팅", "hi": "व्यावसायिक परामर्श", "tr": "İş Danışmanlığı", "nl": "Bedrijfsconsulting", "pl": "Doradztwo Biznesowe"},
    "Income Monitoring": {"es": "Monitoreo de Ingresos", "fr": "Surveillance des Revenus", "de": "Einkommensüberwachung", "pt": "Monitoramento de Renda", "it": "Monitoraggio del Reddito", "ru": "Мониторинг доходов", "zh_HAns": "收入监控", "ar": "مراقبة الدخل", "ja": "収入モニタリング", "ko": "수입 모니터링", "hi": "आय निगरानी", "tr": "Gelir İzleme", "nl": "Inkomstenbewaking", "pl": "Monitorowanie Dochodów"},
    "Insurance Consulting": {"es": "Consultoría de Seguros", "fr": "Conseil en Assurance", "de": "Versicherungsberatung", "pt": "Consultoria de Seguros", "it": "Consulenza Assicurativa", "ru": "Страховой консалтинг", "zh_HAns": "保险咨询", "ar": "استشارات التأمين", "ja": "保険コンサルティング", "ko": "보험 컨설팅", "hi": "बीमा परामर्श", "tr": "Sigorta Danışmanlığı", "nl": "Verzekeringsconsulting", "pl": "Doradztwo Ubezpieczeniowe"},
    "Financial Investment": {"es": "Inversión Financiera", "fr": "Investissement Financier", "de": "Finanzinvestition", "pt": "Investimento Financeiro", "it": "Investimento Finanziario", "ru": "Финансовые инвестиции", "zh_HAns": "金融投资", "ar": "الاستثمار المالي", "ja": "金融投資", "ko": "금융 투자", "hi": "वित्तीय निवेश", "tr": "Finansal Yatırım", "nl": "Financiële Investering", "pl": "Inwestycja Finansowa"},
    "Financial Management": {"es": "Gestión Financiera", "fr": "Gestion Financière", "de": "Finanzverwaltung", "pt": "Gestão Financeira", "it": "Gestione Finanziaria", "ru": "Финансовый менеджмент", "zh_HAns": "财务管理", "ar": "الإدارة المالية", "ja": "財務管理", "ko": "재무 관리", "hi": "वित्तीय प्रबंधन", "tr": "Finansal Yönetim", "nl": "Financieel Beheer", "pl": "Zarządzanie Finansowe"},
    "Software Engineer": {"es": "Ingeniero de Software", "fr": "Ingénieur Logiciel", "de": "Softwareingenieur", "pt": "Engenheiro de Software", "it": "Ingegnere del Software", "ru": "Программный инженер", "zh_HAns": "软件工程师", "ar": "مهندس برمجيات", "ja": "ソフトウェアエンジニア", "ko": "소프트웨어 엔지니어", "hi": "सॉफ्टवेयर इंजीनियर", "tr": "Yazılım Mühendisi", "nl": "Software Ingenieur", "pl": "Inżynier Oprogramowania"},
    "Small Business Owner": {"es": "Dueño de Pequeña Empresa", "fr": "Propriétaire de PME", "de": "Kleinunternehmer", "pt": "Dono de Pequena Empresa", "it": "Proprietario di Piccola Impresa", "ru": "Владелец малого бизнеса", "zh_HAns": "小企业主", "ar": "صاحب عمل صغير", "ja": "中小企業オーナー", "ko": "소기업 사장", "hi": "लघु व्यवसाय स्वामी", "tr": "Küçük İşletme Sahibi", "nl": "Eigenaar Klein Bedrijf", "pl": "Właściciel Małej Firmy"},
    "College Student": {"es": "Estudiante Universitario", "fr": "Étudiant Universitaire", "de": "Student", "pt": "Estudante Universitário", "it": "Studente Universitario", "ru": "Студент колледжа", "zh_HAns": "大学生", "ar": "طالب جامعي", "ja": "大学生", "ko": "대학생", "hi": "कॉलेज छात्र", "tr": "Üniversite Öğrencisi", "nl": "Universiteitsstudent", "pl": "Student"},
    "Investor": {"es": "Inversor", "fr": "Investisseur", "de": "Investor", "pt": "Investidor", "it": "Investitore", "ru": "Инвестор", "zh_HAns": "投资者", "ar": "مستثمر", "ja": "投資家", "ko": "투자자", "hi": "निवेशक", "tr": "Yatırımcı", "nl": "Investeerder", "pl": "Inwestor"},
    "Retired Veteran": {"es": "Veterano Retirado", "fr": "Vétéran à la Retraite", "de": "Pensionierter Veteran", "pt": "Veterano Aposentado", "it": "Veterano Pensionato", "ru": "Ветеран в отставке", "zh_HAns": "退伍军人", "ar": "مخضرم متقاعد", "ja": "退役軍人", "ko": "퇴역 군인", "hi": "सेवानिवृत्त सैनिक", "tr": "Emekli Gazi", "nl": "Gepensioneerde Veteraan", "pl": "Emerytowany Weteran"},
    "Have Questions? We've Got Answers!": {"es": "¿Tiene preguntas? ¡Tenemos respuestas!", "fr": "Des questions? Nous avons les réponses!", "de": "Haben Sie Fragen? Wir haben Antworten!", "pt": "Tem perguntas? Temos respostas!", "it": "Hai domande? Abbiamo le risposte!", "ru": "Есть вопросы? У нас есть ответы!", "zh_HAns": "有疑问？我们来解答！", "ar": "هل لديك أسئلة؟ لدينا الإجابات!", "ja": "ご質問はありますか？お答えします！", "ko": "질문이 있으신가요? 답변해 드립니다!", "hi": "प्रश्न हैं? हमारे पास उत्तर हैं!", "tr": "Sorularınız mı var? Cevaplarımız var!", "nl": "Vragen? Wij hebben de antwoorden!", "pl": "Masz pytania? Mamy odpowiedzi!"},
    "News": {"es": "Noticias", "fr": "Actualités", "de": "Neuigkeiten", "pt": "Notícias", "it": "Notizie", "ru": "Новости", "zh_HAns": "新闻", "ar": "الأخبار", "ja": "ニュース", "ko": "뉴스", "hi": "समाचार", "tr": "Haberler", "nl": "Nieuws", "pl": "Aktualności"},
    "Tips": {"es": "Consejos", "fr": "Conseils", "de": "Tipps", "pt": "Dicas", "it": "Consigli", "ru": "Советы", "zh_HAns": "建议", "ar": "نصائح", "ja": "ヒント", "ko": "팁", "hi": "सुझाव", "tr": "İpuçları", "nl": "Tips", "pl": "Wskazówki"},
    "Create Account": {"es": "Crear Cuenta", "fr": "Créer un Compte", "de": "Konto Erstellen", "pt": "Criar Conta", "it": "Crea Account", "ru": "Создать аккаунт", "zh_HAns": "创建账户", "ar": "إنشاء حساب", "ja": "アカウント作成", "ko": "계정 생성", "hi": "खाता बनाएं", "tr": "Hesap Oluştur", "nl": "Account Aanmaken", "pl": "Utwórz Konto"},
    "Our News & Insights": {"es": "Nuestras Noticias e Insights", "fr": "Nos Actualités et Perspectives", "de": "Neuigkeiten und Einblicke", "pt": "Nossas Notícias e Insights", "it": "Le Nostre Notizie e Approfondimenti", "ru": "Наши новости и аналитика", "zh_HAns": "我们的新闻与洞察", "ar": "أخبارنا ورؤانا", "ja": "ニュースとインサイト", "ko": "뉴스 및 인사이트", "hi": "हमारे समाचार और अंतर्दृष्टि", "tr": "Haberlerimiz ve Görüşlerimiz", "nl": "Ons Nieuws en Inzichten", "pl": "Nasze Aktualności i Spostrzeżenia"},
    "Enter recipient's account number": {"es": "Ingrese el número de cuenta del destinatario", "fr": "Entrez le numéro de compte du destinataire", "de": "Kontonummer des Empfängers eingeben", "pt": "Digite o número da conta do destinatário", "it": "Inserisci il numero di conto del destinatario", "ru": "Введите номер счета получателя", "zh_HAns": "输入收款人账号", "ar": "أدخل رقم حساب المستلم", "ja": "受取人の口座番号を入力", "ko": "수신인의 계좌 번호 입력", "hi": "प्राप्तकर्ता का खाता नंबर दर्ज करें", "tr": "Alıcının hesap numarasını girin", "nl": "Voer het rekeningnummer van de ontvanger in", "pl": "Wpisz numer konta odbiorcy"},
    "Enter amount": {"es": "Ingrese la cantidad", "fr": "Entrez le montant", "de": "Betrag eingeben", "pt": "Digite o valor", "it": "Inserisci l'importo", "ru": "Введите сумму", "zh_HAns": "输入金额", "ar": "أدخل المبلغ", "ja": "金額を入力", "ko": "금액 입력", "hi": "राशि दर्ज करें", "tr": "Tutarı girin", "nl": "Voer bedrag in", "pl": "Wprowadź kwotę"},
    "Enter reason for transfer": {"es": "Ingrese el motivo de la transferencia", "fr": "Entrez la raison du transfert", "de": "Grund für Überweisung eingeben", "pt": "Digite o motivo da transferência", "it": "Inserisci il motivo del trasferimento", "ru": "Введите причину перевода", "zh_HAns": "输入转账原因", "ar": "أدخل سبب التحويل", "ja": "送金理由を入力", "ko": "이체 이유 입력", "hi": "स्थानांतरण का कारण दर्ज करें", "tr": "Transfer nedenini girin", "nl": "Voer reden voor overboeking in", "pl": "Wpisz powód przelewu"},
}

def escape_po_string(s):
    """Escape a string for use in a .po file msgstr."""
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n"\n"')
    return s

def update_po_file(lang_code, translations):
    """Update a .po file with the given translations."""
    locale_dir = lang_code if lang_code != 'zh_HAns' else 'zh_HAns'
    po_path = os.path.join('locale', locale_dir, 'LC_MESSAGES', 'django.po')

    if not os.path.exists(po_path):
        print(f"  File not found: {po_path}")
        return 0

    with open(po_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Fix header: remove fuzzy marker and set language
    display_lang = lang_code.replace('_HAns', '-hans')
    content = content.replace('#, fuzzy\n', '')
    content = content.replace('"Language: \\n"', f'"Language: {display_lang}\\n"')

    count = 0
    for msgid, lang_map in translations.items():
        if lang_code not in lang_map:
            continue
        msgstr = lang_map[lang_code]
        if not msgstr:
            continue

        # Build the pattern to find this specific msgid block with empty msgstr
        escaped_msgid = re.escape(msgid)
        # Match msgid "..." followed by msgstr "" (possibly multiline msgid)
        pattern = r'(msgid "' + escaped_msgid + r'"\nmsgstr )""\n'
        replacement = r'\1"' + escape_po_string(msgstr) + '"\n'
        new_content, n = re.subn(pattern, replacement, content)
        if n > 0:
            content = new_content
            count += 1

    with open(po_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return count

total = 0
for lang in LANGUAGES:
    n = update_po_file(lang, TRANSLATIONS)
    print(f"  {lang}: updated {n} translations")
    total += n

print(f"\nTotal: {total} translations written across {len(LANGUAGES)} languages")
print("\nNow compile with: python manage.py compilemessages")
