# Generated by Django 5.1.3 on 2025-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
