# Generated by Django 5.1.3 on 2025-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
