# Generated by Django 5.1.3 on 2025-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bankaccount_transaction_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(blank=True, help_text='PayPal email (public receiving address).', max_length=254, null=True)),
                ('cashapp_tag', models.CharField(blank=True, help_text='CashApp $tag (e.g. $StarlinkPay).', max_length=100, null=True)),
                ('bitcoin_address', models.CharField(blank=True, help_text='Bitcoin (BTC) address.', max_length=200, null=True)),
                ('active', models.BooleanField(default=True, help_text='If False, hide from public pages.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Details',
                'verbose_name_plural': 'Payment Details',
            },
        ),
    ]
