# Generated by Django 5.1.3 on 2025-10-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_message_options_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction_pin',
        ),
    ]
