# Generated by Django 5.1.3 on 2026-01-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currenyz_code',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
