# Generated by Django 5.1.3 on 2026-01-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_bankaccount_currency_symbol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='currenyz_code',
            new_name='currency_code',
        ),
    ]
