# Generated by Django 6.0.6 on 2026-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chat_photos/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cashapp_tag',
            field=models.CharField(blank=True, help_text='CashApp $tag (e.g. $Starlink Pay).', max_length=100, null=True),
        ),
    ]
